version: '3'

services:
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./front:/app
      - /app/node_modules/
    restart: always
    depends_on:
      - back

  back:
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file: ./back/.docker.env
    ports:
      - 8000:8000
    volumes:
      - ./back:/app
      - /app/node_modules/
    restart: always
    depends_on:
      - db

  db:
    container_name: db
    image: mongo:6.0.6
    volumes:
      - data:/data/db
    restart: always
    expose:
      - 27017

volumes:
  data:
