version: '3'

services:
  front:
    container_name: front
    build:
      dockerfile: Dockerfile.front
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - back

  back:
    container_name: back
    build:
      dockerfile: Dockerfile.back
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db

  db:
    container_name: db
    image: mongo:6.0.6
    volumes:
      - data:/data/db
    restart: always
    expose:
      - 27017

volumes:
  data:
