import { Container } from '@mui/material';
import { type Metadata } from 'next';
import { Inter } from 'next/font/google';
import { type ReactElement, type ReactNode } from 'react';

import { Header } from '@/components';
import Providers from '@/lib/Providers';

import './ui/globals.css';
import './ui/custom.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: { template: '%s | Website project', default: 'Website project' },
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico?v=2',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): ReactElement {
  return (
    <html lang="en" data-bs-theme="dark">
      <body className={inter.className}>
        <Providers>
          <Header />
          <main>
            <Container>{children}</Container>
          </main>
        </Providers>
      </body>
    </html>
  );
}
