import { Header } from '@/components';
import Providers from '@/lib/Providers';
import { type Metadata } from 'next';
import { Inter } from 'next/font/google';
import './ui/globals.css';
import './ui/custom.scss';
import { type ReactNode, type ReactElement } from 'react';
import { Container } from 'react-bootstrap';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: { template: '%s | Website project', default: 'Website project' },
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico?v=2',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): ReactElement {
  return (
    <html lang="en" data-bs-theme="dark">
      <Providers>
        <body className={inter.className}>
          <Header />
          <main>
            <Container>{children}</Container>
          </main>
        </body>
      </Providers>
    </html>
  );
}
