name: Build and publish Docker images

on:
  push:
    branches: [main]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      front-changed: ${{ steps.filter.outputs.front }}
      back-changed: ${{ steps.filter.outputs.back }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Path filtering
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            front:
              - '.github/workflows/ghcr.yml'
              - 'apps/front/**'
              - 'packages/shared-types/**'
              - 'Dockerfile.front'
              - 'yarn.lock'
            back:
              - '.github/workflows/ghcr.yml'
              - 'apps/back/**'
              - 'packages/shared-types/**'
              - 'Dockerfile.back'
              - 'yarn.lock'

  docker-front:
    needs: check-changes
    if: needs.check-changes.outputs.front-changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/front
          tags: |
            type=sha
            type=raw,value=latest

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.front
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v2
      #   with:
      #     subject-name: ghcr.io/${{ github.repository }}/front
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true

  docker-back:
    needs: check-changes
    if: needs.check-changes.outputs.back-changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/back
          tags: |
            type=sha
            type=raw,value=latest

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.back
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v2
      #   with:
      #     subject-name: ghcr.io/${{ github.repository }}/back
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true
